# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160512_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
